# Generated by Django 5.2 on 2025-04-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_birth_date_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
