# Generated by Django 5.2 on 2025-04-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(max_length=255)),
                ('totalSales', models.PositiveIntegerField(default=0)),
                ('totalOrders', models.PositiveIntegerField(default=0)),
                ('totalRevenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRevenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='products.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to='sales.salesreport')),
            ],
            options={
                'unique_together': {('product', 'report')},
            },
        ),
    ]
